title: 개발일지 # your site title
author: June
email: potados99@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  개발일지 겸 공부한 것 적어놓는 저장소이자 일기장입니다.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: # replace with your_twitter_username or comment to remove link from footer
github_username: potados99 # replace with your_github_username or comment to remove link from footer
instagram_username: # replace with your_instagram_username or comment to remove link from footer
social:
  name: Song Pyong Jun
  links:
    - https://www.facebook.com/potados99
    - https://github.com/potados99

disqus:
  shortname: # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
#theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
